[package]
name = "web_page_axum"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0"
serde = { version = "1", features = ["derive"] }
mime_guess = "2"
tokio-util = { version = "0", features = ["io"] }
sqlx = "0"

[profile.release]
strip = "debuginfo"
panic = "abort"
opt-level = 3
codegen-units = 1